COLORS_SRC  = colors.toml

# tmux
TMUX_CONFIG_DIR = /tmux/.config/tmux/
TMUX_COLORS     = tmux/.config/tmux/colors.tmux.conf

# Starship
STARSHIP_BASE   = starship/.config/starship_base.toml
STARSHIP_CONFIG = starship/.config/starship.toml

# nvim
NVIM_CONFIG_DIR = nvim/.config/nvim
NVIM_COLORS     = $(NVIM_CONFIG_DIR)/lua/custom/generated_colors.lua

# bash
BASH_COLORS = bash/.config/bash/bash_color

STOW = vim tmux starship nvim bash

.PHONY: all stow apply clean install

all: create apply stow

# Creates all needed paths for all configs to work
install: setup.sh
	@chmod +x ./setup.sh
	@./setup.sh

# apply the new colorscheme to the whole enviroment
apply: $(COLORS_SRC) $(BASH_COLORS) $(STARSHIP_CONFIG) $(TMUX_COLORS) $(NVIM_COLORS)

$(BASH_COLORS): $(COLORS_SRC)
	@@echo "Generating Bash Color environment variables..."
	@echo "# Generated by Makefile - do not edit" > $@
	@awk -F'=' '/=/ && !/\[/ { \
		gsub(/[ "]/, "", $$1); \
		gsub(/[ "]/, "", $$2); \
		print "export COLOR_" toupper($$1) "=\"" $$2 "\"" \
	}' $(COLORS_SRC) >> $@

$(STARSHIP_CONFIG): $(COLORS_SRC)
	@echo "Generating Starship colors..."
	@echo "palette = \"onedark_ansii\"\n" > $@
	@cat $(STARSHIP_BASE) >> $@
	@printf "\n" >> $@
	@cat $(COLORS_SRC) >> $@

$(TMUX_COLORS): $(COLORS_SRC)
	@echo "Generating Tmux colors..."
	@echo "# Generated by Makefile - do not edit" > $@
	@awk -F'=' '/=/ && !/\[/ { \
		gsub(/[ "]/, "", $$1); \
		gsub(/[ "]/, "", $$2); \
		print "set -g @" $$1 " \"" $$2 "\""}' \
		$(COLORS_SRC) >> $@
	@tmux source-file $(TMUX_CONFIG_DIR)/tmux.conf

$(NVIM_COLORS): $(COLORS_SRC)
	@echo "Generating Neovim colors..."
	@echo "-- Generated by Makefile - do not edit manually" > $@
	@echo "return {" >> $@
	@# 1. Split by # to remove comments
	@# 2. Split by = to get key/value
	@# 3. Clean up whitespace and quotes
	@awk -F'[=]' '/=/ && !/\[/ { \
		gsub(/[[:space:]]/, "", $$1); \
		gsub(/[[:space:]"]/, "", $$2); \
		print "  " $$1 " = \"" $$2 "\"," \
	}' $(COLORS_SRC) >> $@
	@echo "}" >> $@

# stows everything
stow:
	stow -R $(foreach dir, $(STOW), $(dir))
