#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""color_file_gen.py

Generate tool-specific color files (nvim, tmux, ...) from a single tiered
colors.toml palette (primitives -> semantics -> components).

Usage:
    uv run color_file_gen.py [--config colors.toml] \
        <id> <name> <file_type> <dir>  [<id> <name> <file_type> <dir> ...]

Each 4-tuple is resolved independently:
    id         key under [components.<id>] to read colors from
    name       base filename of the generated file (without extension)
    file_type  output format: toml | bash | lua | conf (see FORMATTERS
               below to add more)
    dir        output directory, relative to the current working directory

Example:
    uv run color_file_gen.py \
        nvim colors.nvim lua   config/nvim/lua \
        tmux colors.tmux conf  config/tmux

    -> config/nvim/lua/colors.nvim.lua
    -> config/tmux/colors.tmux.conf
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Callable, NoReturn

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        sys.exit(
            "error: Python 3.11+ is required for 'tomllib'. "
            "`uv run` will fetch a suitable interpreter automatically; "
            "otherwise `pip install tomli` as a fallback."
        )


GENERATED_HEADER = "Generated by color_file_gen.py -- do not edit by hand."


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


def die(message: str) -> NoReturn:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


# ---------------------------------------------------------------------------
# Color resolution
# ---------------------------------------------------------------------------


def load_palette(path: Path) -> dict:
    if not path.is_file():
        die(f"colors file not found: {path}")
    try:
        with path.open("rb") as f:
            return tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        die(f"failed to parse '{path}': {exc}")


def resolve_path(dotted_path: str, root: dict) -> object:
    """Walk a dotted path (e.g. 'primitives.green.500') against the parsed
    document and return whatever value lives there."""
    node: object = root
    parts = dotted_path.split(".")
    for i, part in enumerate(parts):
        if not isinstance(node, dict) or part not in node:
            walked = ".".join(parts[: i + 1])
            if walked == dotted_path:
                raise KeyError(f"'{walked}' does not exist")
            raise KeyError(f"'{walked}' does not exist (looked up via '{dotted_path}')")
        node = node[part]
    return node


def resolve_color(value: object, root: dict, _chain: tuple[str, ...] = ()) -> str:
    """Resolve a raw TOML value down to a literal hex color string,
    following 'a.b.c' style references through as many tiers as needed
    (component -> semantic -> primitive, or any other depth)."""
    if isinstance(value, str) and value.startswith("#"):
        return value
    if not isinstance(value, str):
        raise TypeError(f"expected a hex color or 'a.b.c' reference, got {value!r}")
    if value in _chain:
        raise ValueError("circular reference: " + " -> ".join((*_chain, value)))
    return resolve_color(resolve_path(value, root), root, (*_chain, value))


def flatten(section: dict, prefix: str = "") -> dict[str, object]:
    """Flatten nested tables under a component into dotted keys, so e.g.
    components.nvim.syntax.comment becomes the key 'syntax.comment'."""
    flat: dict[str, object] = {}
    for key, value in section.items():
        full_key = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            flat.update(flatten(value, full_key))
        else:
            flat[full_key] = value
    return flat


def sanitize_key(key: str) -> str:
    """Turn a (possibly dotted) component key into a safe identifier for
    bash/lua variable names and tmux user options."""
    safe = re.sub(r"\W", "_", key)
    if safe and safe[0].isdigit():
        safe = f"_{safe}"
    return safe


def get_component_colors(component_id: str, root: dict) -> dict[str, str]:
    """Step 2+3 of the flow: find [components.<id>], resolve every entry
    in it down to a literal hex color."""
    components = root.get("components", {})
    if component_id not in components:
        available = ", ".join(sorted(components)) or "(none defined)"
        die(
            f"no [components.{component_id}] section in colors file. "
            f"Available components: {available}"
        )
    section = components[component_id]
    if not isinstance(section, dict):
        die(f"[components.{component_id}] is not a table")

    resolved: dict[str, str] = {}
    for key, value in flatten(section).items():
        try:
            resolved[sanitize_key(key)] = resolve_color(value, root)
        except (KeyError, ValueError, TypeError) as exc:
            die(f"failed to resolve '{component_id}.{key}': {exc}")
    return resolved


# ---------------------------------------------------------------------------
# Formatters -- add a new file_type by writing a function of the form
# (component_id, colors) -> str and registering it in FORMATTERS.
# ---------------------------------------------------------------------------

Formatter = Callable[[str, dict[str, str]], str]


def format_toml(component_id: str, colors: dict[str, str]) -> str:
    lines = [f"# {GENERATED_HEADER}", f"# component: {component_id}", ""]
    lines += [f'{key} = "{value}"' for key, value in colors.items()]
    return "\n".join(lines) + "\n"


def format_bash(component_id: str, colors: dict[str, str]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        f"# {GENERATED_HEADER}",
        f"# component: {component_id}",
        "",
    ]
    lines += [f'export {key}="{value}"' for key, value in colors.items()]
    return "\n".join(lines) + "\n"


def format_lua(component_id: str, colors: dict[str, str]) -> str:
    lines = [f"-- {GENERATED_HEADER}", f"-- component: {component_id}", "", "return {"]
    lines += [f'  {key} = "{value}",' for key, value in colors.items()]
    lines.append("}")
    return "\n".join(lines) + "\n"


def format_conf(component_id: str, colors: dict[str, str]) -> str:
    # tmux-style: each color becomes a user option, referenced elsewhere in
    # your tmux.conf as #{@key}. This keeps it usable directly as a `conf`
    # tmux can `source-file`, rather than guessing at real tmux option names.
    lines = [f"# {GENERATED_HEADER}", f"# component: {component_id}", ""]
    lines += [f'set -g @{key} "{value}"' for key, value in colors.items()]
    return "\n".join(lines) + "\n"


FORMATTERS: dict[str, Formatter] = {
    "toml": format_toml,
    "bash": format_bash,
    "lua": format_lua,
    "conf": format_conf,
}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None) -> tuple[str, list[tuple[str, str, str, str]]]:
    parser = argparse.ArgumentParser(
        prog="color_file_gen.py",
        description="Generate tool-specific color files from a tiered colors.toml palette.",
        epilog=(
            "example:\n"
            "  uv run color_file_gen.py \\\n"
            "      nvim colors.nvim lua  config/nvim/lua \\\n"
            "      tmux colors.tmux conf config/tmux\n\n"
            "  -> config/nvim/lua/colors.nvim.lua\n"
            "  -> config/tmux/colors.tmux.conf\n\n"
            "note: put --config before the id/name/file_type/dir groups."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-c",
        "--config",
        default="colors.toml",
        help="path to the source colors.toml (default: %(default)s), relative to CWD",
    )
    parser.add_argument(
        "entries",
        nargs="+",
        metavar="ARG",
        help="repeating group of 4 positional values: id name file_type dir",
    )
    args = parser.parse_args(argv)

    if len(args.entries) % 4 != 0:
        parser.error(
            "positional arguments must come in groups of 4 "
            f"(id name file_type dir); got {len(args.entries)} value(s)"
        )

    groups = [tuple(args.entries[i : i + 4]) for i in range(0, len(args.entries), 4)]
    return args.config, groups


def main(argv: list[str] | None = None) -> None:
    config_path, groups = parse_args(argv)
    root = load_palette(Path(config_path).expanduser())

    for component_id, name, file_type, dir_arg in groups:
        formatter = FORMATTERS.get(file_type.lower())
        if formatter is None:
            supported = ", ".join(sorted(FORMATTERS))
            die(f"unsupported file_type '{file_type}'. Supported types: {supported}")

        colors = get_component_colors(component_id, root)
        content = formatter(component_id, colors)

        out_dir = Path(dir_arg).expanduser()
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{name}.{file_type}"
        out_path.write_text(content, encoding="utf-8")
        print(f"[ok] components.{component_id} -> {out_path}  ({len(colors)} colors)")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\naborted", file=sys.stderr)
        raise SystemExit(130)
