# Basic ls aliases
alias ll='ls -alF'
alias lsa='ls -a'
alias la='ls -A'
alias l='ls -CF'
alias rmd='rm -r'
alias rmdf='rm -rf'
alias mkdirp='mkdir -p'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

