# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Local script for machine dependent settings
touch $HOME/.dotfiles/bash/.config/bash/local_script.sh
. $HOME/.dotfiles/bash/.config/bash/local_script.sh

# XDG Base Directory Specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# Ensure the directories actually exist
mkdir -p "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME" "$XDG_STATE_HOME"

# Change history path to match XDG standards
export HISTFILE="$XDG_STATE_HOME/bash/history"

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r $XDG_CONFIG_HOME/bash/dircolors && eval "$(dircolors -b $XDG_CONFIG_HOME/bash/dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Alias definitions.
if [ -f $XDG_CONFIG_HOME/bash/bash_aliases ]; then
    . $XDG_CONFIG_HOME/bash/bash_aliases
fi

# --- export enviroment variables here ---
# Java
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
export JASMIN_JAR="$XDG_DATA_HOME/jasmin/jasmin.jar"

# Git
export GIT_CONFIG="$XDG_CONFIG_HOME/git/config"

# Add PATH variables
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:$JASMIN_JAR"
export PATH="$PATH:$HOME/.local/bin"

# Load Color enviroment variables
if [ -f $XDG_CONFIG_HOME/bash/bash_color ]; then
	. $XDG_CONFIG_HOME/bash/bash_color
fi

# Background color
if [[ $TERM != "linux" ]]; then
    printf "\e]11;%s\a" "$COLOR_BG0"
fi

# Enable starship
eval "$(starship init bash)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/christian/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/christian/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/christian/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/christian/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

